version: "2"
services:
  shop_ecommerce:
    container_name: shop_ecommerce
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '3001:3000'
    restart: always
    networks:
        - default
    volumes: 
        - shop_ecommerce: ./data/shop
